import { GRAY_1, GRAY_5, GRAY_6, SUNFLOWER } from "./colors";

export { GRAY_1, GRAY_5, GRAY_6, SUNFLOWER };

const IS_REGISTER_ENABLED = false;
const IS_STATISTICS_ENABLED = false;

export { IS_REGISTER_ENABLED, IS_STATISTICS_ENABLED };
