export const RouteName = {
  Admin: 'admin',
  Games: 'games',
  Home: 'home',
  Match: 'match',
  Overview: 'overview',
  Personal: 'personal',
  Player: 'player',
  Register: 'register',
  Results: 'results',
  Rules: 'rules',
  SignIn: 'sign-in',
  Team: 'team',
  TeamsStatistics: 'teams-statistics',
} as const;

export const RoutePath = {
  Admin: '/admin',
  Games: '/games',
  Home: '/home',
  Match: '/match/:gameId',
  Overview: '/overview',
  Personal: '/personal',
  Player: '/player/:userId',
  Register: '/register',
  Results: '/results',
  Root: '/',
  Rules: '/rules',
  SignIn: '/sign-in',
  Team: '/team/:teamId',
  TeamsStatistics: '/teams-statistics',
} as const;
